# Site Settings
url: "https://jldevictoria.github.io"
baseurl: ""
author: Joseph DeVictoria
title: [#!]
email: jldevictoria@gmail.com
description: A place to store random essays to share with my friends
encoding: utf-8

# Google Analytics
google_analytics: UA-65518086-4

# Disqus
disqus:
    shortname: jldevictoria

# Social Media Contact
twitter_username: jldevictoria
github_username:  jldevictoria

# Build settings
markdown: kramdown
theme: minima
